### PR TITLE
Bug: Fix label line-height.

### LINKED ISSUE #81: Fix label line-height
The line-height in `<label />`s is incorrect and too tight in comparison to other elements.

### PR DESCRIPTION
**Pull request by ChrisBrettCA**
When labels spill over to a couple lines, the line-height was too tight. This has been brought into line with the line-height of paragraph text now.

Resolves #81

### CODE REVIEW

**Comment by ChrisBrettCA** [comment]
@adamgparsons can you check this through, and either suggest changes, make changes yourself etc on this branch? Thanks

**Comment by adam-parsons-ca** [comment]
Hi @ChrisBrettCA and @btomy, please review commit ba53d1c. I have adjusted the markup in the documentation website to ensure line spacing is correct when a hint is used.

**Comment by btomy** [comment]
@ChrisBrettCA @adam-parsons-ca i have tested this, but still missing the line-height for `c-label` : 1.5;

**Comment by adam-parsons-ca** [comment]
@ChrisBrettCA and @btomy. Please review the latest commit. I have added the line height which fixes the spacing issue. I have done this matching the structure of the typography.scss page.

**Pull request closed without merging**
